# **DEKOMPOSISI MATRIKS**

## Melakukan Dekomposisi LU

In [4]:
import numpy as np

A = np.array([
    [4, 2, 3, 1],
    [6, 3, 4, 2],
    [2, 1, 1, 0],
    [8, 4, 5, 3]
], dtype=float)

print("Matriks A:")
print(A)

def lu_decomposition(A):
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        # Upper triangular
        for k in range(i, n):
            U[i][k] = A[i][k] - sum(L[i][j] * U[j][k] for j in range(i))

        # Lower triangular
        L[i][i] = 1
        for k in range(i+1, n):
            L[k][i] = (A[k][i] - sum(L[k][j] * U[j][i] for j in range(i))) / U[i][i]

    return L, U

L, U = lu_decomposition(A)

print("Matriks L:")
print(L)

print("\nMatriks U:")
print(U)

print("\nVerifikasi A ≈ L @ U:")
print(L @ U)


Matriks A:
[[4. 2. 3. 1.]
 [6. 3. 4. 2.]
 [2. 1. 1. 0.]
 [8. 4. 5. 3.]]
Matriks L:
[[1.  0.  0.  0. ]
 [1.5 1.  0.  0. ]
 [0.5 nan 1.  0. ]
 [2.  nan nan 1. ]]

Matriks U:
[[ 4.   2.   3.   1. ]
 [ 0.   0.  -0.5  0.5]
 [ 0.   0.   nan  nan]
 [ 0.   0.   0.   nan]]

Verifikasi A ≈ L @ U:
[[ 4.  2. nan nan]
 [ 6.  3. nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]


C:\Users\Microsoft\AppData\Local\Temp\ipykernel_12236\1317786993.py:26: RuntimeWarning: invalid value encountered in scalar divide
  L[k][i] = (A[k][i] - sum(L[k][j] * U[j][i] for j in range(i))) / U[i][i]


## Melakukan Dekomposisi QR

## Menghitung Eigenvalue dan Eigenvector

## Menuliskan  Interpretasi 