# **DEKOMPOSISI MATRIKS**

## Melakukan Dekomposisi LU

In [9]:
import numpy as np

A = np.array([
    [2, 3, 1, 5],
    [4, 7, 7, 17],
    [-2, 4, 5, 10],
    [6, 18, 22, 61]
], dtype=float)

def lu_doolittle(A):
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        # Diagonal L = 1
        L[i, i] = 1

        # Menghitung elemen U
        for j in range(i, n):
            U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))

        # Menghitung elemen L
        for j in range(i + 1, n):
            L[j, i] = (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]

    return L, U

L, U = lu_doolittle(A)

print("Matriks A:")
print(A)

print("\nMatriks L:")
print(L)

print("\nMatriks U:")
print(U)

A_rekonstruksi = L @ U

print("\nHasil perkalian L @ U:")
print(A_rekonstruksi)

print("\nApakah A = L @ U?")
print(np.allclose(A, A_rekonstruksi))


Matriks A:
[[ 2.  3.  1.  5.]
 [ 4.  7.  7. 17.]
 [-2.  4.  5. 10.]
 [ 6. 18. 22. 61.]]

Matriks L:
[[ 1.          0.          0.          0.        ]
 [ 2.          1.          0.          0.        ]
 [-1.          7.          1.          0.        ]
 [ 3.          9.          0.89655172  1.        ]]

Matriks U:
[[  2.           3.           1.           5.        ]
 [  0.           1.           5.           7.        ]
 [  0.           0.         -29.         -34.        ]
 [  0.           0.           0.          13.48275862]]

Hasil perkalian L @ U:
[[ 2.  3.  1.  5.]
 [ 4.  7.  7. 17.]
 [-2.  4.  5. 10.]
 [ 6. 18. 22. 61.]]

Apakah A = L @ U?
True


## Melakukan Dekomposisi QR

In [12]:
import numpy as np

# ======================================================
# 1. Mendefinisikan matriks A (4x4)
# ======================================================
# Matriks ini akan didekomposisi menjadi Q dan R
A = np.array([
    [2, 3, 1, 5],
    [4, 7, 7, 17],
    [-2, 4, 5, 10],
    [6, 18, 22, 61]
], dtype=float)

print("Matriks A:")
print(A)

# ======================================================
# 2. Melakukan dekomposisi QR
# ======================================================
# Fungsi np.linalg.qr() mengembalikan:
# Q : matriks ortogonal (Q^T Q = I)
# R : matriks segitiga atas
Q, R = np.linalg.qr(A)

print("\nMatriks Q (ortogonal):")
print(Q)

print("\nMatriks R (segitiga atas):")
print(R)

# ======================================================
# 3. Verifikasi bahwa A ≈ Q @ R
# ======================================================
# Mengalikan Q dan R untuk merekonstruksi matriks A
A_rekonstruksi = Q @ R

print("\nHasil perkalian Q @ R:")
print(A_rekonstruksi)

# Mengecek apakah A dan Q@R hampir sama
# Digunakan 'allclose' karena perhitungan numerik
print("\nApakah A ≈ Q @ R?")
print(np.allclose(A, A_rekonstruksi))

# ======================================================
# 4. Verifikasi tambahan: Ortogonalitas matriks Q
# ======================================================
# Jika Q benar-benar ortogonal, maka Q^T @ Q = I
QTQ = Q.T @ Q

print("\nHasil Q^T @ Q (harus mendekati matriks identitas):")
print(QTQ)


Matriks A:
[[ 2.  3.  1.  5.]
 [ 4.  7.  7. 17.]
 [-2.  4.  5. 10.]
 [ 6. 18. 22. 61.]]

Matriks Q (ortogonal):
[[-0.25819889 -0.14760447 -0.83937747 -0.45496343]
 [-0.51639778 -0.19456953 -0.23985966  0.79871357]
 [ 0.25819889  0.85208037 -0.37174307  0.26286776]
 [-0.77459667  0.46294131  0.31578457 -0.29319865]]

Matriks R (segitiga atas):
[[ -7.74596669 -17.29932561 -19.62311562 -54.73816463]
 [  0.           9.93646483  12.93551937  32.71451892]
 [  0.           0.           2.57015016   7.27092669]
 [  0.           0.           0.          -3.95312667]]

Hasil perkalian Q @ R:
[[ 2.  3.  1.  5.]
 [ 4.  7.  7. 17.]
 [-2.  4.  5. 10.]
 [ 6. 18. 22. 61.]]

Apakah A ≈ Q @ R?
True

Hasil Q^T @ Q (harus mendekati matriks identitas):
[[ 1.00000000e+00  4.57278081e-17  3.29128858e-16  8.28612748e-17]
 [ 4.57278081e-17  1.00000000e+00 -2.49582723e-18  1.64905189e-16]
 [ 3.29128858e-16 -2.49582723e-18  1.00000000e+00 -4.04790639e-17]
 [ 8.28612748e-17  1.64905189e-16 -4.04790639e-17  1.000

## Menghitung Eigenvalue dan Eigenvector

## Menuliskan  Interpretasi 