# **OPERASI DASAR MATRIKS**

## PENJUMLAHAN MATRIKS

In [ ]:
import numpy as np

# FUNGSI PENJUMLAHAN MATRIKS
def penjumlahan_matriks(A, B):
    """
    Menjumlahkan dua matriks 2x2
    Syarat: Ukuran matriks A dan B harus sama
    """
    return A + B

A1 = np.array([
            [1, 2],
            [3, 4]
            ])
B1 = np.array([
            [5, 6],
            [7, 8]
            ])
A2 = np.array([
            [0, 0],
            [0, 0]
            ])
B2 = np.array([
            [2, 3],
            [4, 5]
            ])
A3 = np.array([
            [-1, 2],
            [3, -4]
            ])
B3 = np.array([
            [4, -2],
            [-3, 1]
            ])
print("=== TEST CASE PENJUMLAHAN MATRIKS ===")

# Test Case 1
print("Input:\n", A1, "\n+\n", B1)
print("Output:\n", penjumlahan_matriks(A1, B1))

# Test Case 2
print("\nInput:\n", A2, "\n+\n", B2)
print("Output:\n", penjumlahan_matriks(A2, B2))
# Penjelasan:
# Matriks nol tidak mengubah nilai matriks lain

# Test Case 3
print("\nInput:\n", A3, "\n+\n", B3)
print("Output:\n", penjumlahan_matriks(A3, B3))
# Penjelasan:
# Bilangan negatif dan positif dijumlahkan normal

=== TEST CASE PENJUMLAHAN MATRIKS ===
Input:
 [[1 2]
 [3 4]] 
+
 [[5 6]
 [7 8]]
Output:
 [[ 6  8]
 [10 12]]

Input:
 [[0 0]
 [0 0]] 
+
 [[2 3]
 [4 5]]
Output:
 [[2 3]
 [4 5]]

Input:
 [[-1  2]
 [ 3 -4]] 
+
 [[ 4 -2]
 [-3  1]]
Output:
 [[ 3  0]
 [ 0 -3]]


## PENGURANGAN MATRIKS

In [ ]:
import numpy as np
def pengurangan_matriks(A, B):
    """
    Mengurangkan matriks B dari matriks A
    """
    return A - B

A1 = np.array([
            [1, 2],
            [3, 4]
            ])
B1 = np.array([
            [5, 6],
            [7, 8]
            ])
A2 = np.array([
            [0, 0],
            [0, 0]
            ])
B2 = np.array([
            [2, 3],
            [4, 5]
            ])
A3 = np.array([
            [-1, 2],
            [3, -4]])
B3 = np.array([
            [4, -2],
            [-3, 1]
            ])
print("\n=== TEST CASE PENGURANGAN MATRIKS ===")
# Test Case 1

print("SHAPE:", A1.shape)
print("Input:\n", A1, "\n-\n", B1)
print("Output:\n", pengurangan_matriks(A1, B1))

# Test Case 2
print("\nInput:\n", B2, "\n-\n", A2)
print("Output:\n", pengurangan_matriks(B2, A2))
# Penjelasan:
# Matriks nol tidak mengubah nilai matriks lain

# Test Case 3

print("\nInput:\n", A3, "\n+\n", B3)
print("Output:\n", pengurangan_matriks(A3, B3))
# Penjelasan:
# Bilangan negatif dan positif dijumlahkan normal


=== TEST CASE PENGURANGAN MATRIKS ===
SHAPE: (2, 2)
Input:
 [[1 2]
 [3 4]] 
-
 [[5 6]
 [7 8]]
Output:
 [[-4 -4]
 [-4 -4]]

Input:
 [[2 3]
 [4 5]] 
-
 [[0 0]
 [0 0]]
Output:
 [[2 3]
 [4 5]]

Input:
 [[-1  2]
 [ 3 -4]] 
+
 [[ 4 -2]
 [-3  1]]
Output:
 [[-5  4]
 [ 6 -5]]


## PERKALIAN MATRIKS

In [ ]:
import numpy as np
def perkalian_matriks(A, B):
    """
    Mengalikan dua matriks menggunakan perkalian matriks (dot product)
    """
    return np.dot(A, B)

A1 = np.array([
            [1, 2],
            [3, 4]
            ])
B1 = np.array([
            [5, 6],
            [7, 8]
            ])
A2 = np.array([
            [0, 0],
            [0, 0]
            ])
B2 = np.array([
            [2, 3],
            [4, 5]
            ])

A3 = np.array([
            [-1, 2],
            [3, -4]])
B3 = np.array([
            [4, -2],
            [-3, 1]])

print("\n=== TEST CASE PERKALIAN MATRIKS ===")

# Test Case 1
print("Input:\n", A1, "\nx\n", B1)
print("Output:\n", perkalian_matriks(A1, B1))

# Test Case 2
print("\nInput:\n", B2, "\nx\n", A2)
print("Output:\n", perkalian_matriks(B2, A2))
# Penjelasan:
# Matriks nol tidak mengubah nilai matriks lain

# Test Case 3
print("\nInput:\n", A3, "\nx\n", B3)
print("Output:\n", perkalian_matriks(A3, B3))


=== TEST CASE PERKALIAN MATRIKS ===
Input:
 [[1 2]
 [3 4]] 
x
 [[5 6]
 [7 8]]
Output:
 [[19 22]
 [43 50]]

Input:
 [[2 3]
 [4 5]] 
x
 [[0 0]
 [0 0]]
Output:
 [[0 0]
 [0 0]]

Input:
 [[-1  2]
 [ 3 -4]] 
x
 [[ 4 -2]
 [-3  1]]
Output:
 [[-10   4]
 [ 24 -10]]


## DETERMINAN MATRIKS

In [ ]:
import numpy as np

# FUNGSI DETERMINAN MATRIKS
def determinan_matriks(A):
    """
    Menghitung determinan matriks 2x2
    Rumus manual 2x2:
    |a b|
    |c d|  = ad - bc
    """
    return np.linalg.det(A)
A1 = np.array([
            [1, 2],
            [3, 4]
            ])
B1 = np.array([
            [5, 6],
            [7, 8] 
            ])
A2 = np.array([
            [0, 0],
            [0, 0]])
B2 = np.array([
            [2, 3],
            [4, 5]
            ])
A3 = np.array([
            [-1, 2],
            [3, -4]
            ])
B3 = np.array([
            [4, -2],
            [-3, 1]
            ])

print("\n=== TEST CASE DETERMINAN MATRIKS ===")

# Test Case 1
print("Determinant A1:", determinan_matriks(A1))
# Penjelasan:
# Determinan = (1*4) - (2*3) = -2

# Test Case 2
A4 = np.array([[1, 2],
            [2, 4]])
print("Determinant A4:", determinan_matriks(A4))
# Penjelasan:
# Baris saling bergantung → determinan = 0

# Test Case 3
print("Determinant A3:", determinan_matriks(A3))
# Penjelasan:
# Determinan ≠ 0, maka matriks invertible


=== TEST CASE DETERMINAN MATRIKS ===
Determinant A1: -2.0000000000000004
Determinant A4: 0.0
Determinant A3: -2.0000000000000004


## INVERS MATRIKS

In [ ]:
import numpy as np
def invers_matriks(A):
    """
    Menghitung invers matriks jika determinan ≠ 0
    Jika determinan = 0, matriks tidak memiliki invers
    """
    det = np.linalg.det(A)
    if det == 0:
        return "Matriks tidak invertible (determinan = 0)"
    else:
        return np.linalg.inv(A)

A1 = np.array([
            [1, 2],
            [3, 4]
            ])
B1 = np.array([
            [5, 6],
            [7, 8]
            ])

A2 = np.array([
            [0, 0],
            [0, 0]
            ])
B2 = np.array([
            [2, 3],
            [4, 5]
            ])

A3 = np.array([
            [-1, 2],
            [3, -4]
            ])
B3 = np.array([
            [4, -2],
            [-3, 1]
            ])

print("\n=== TEST CASE INVERS MATRIKS ===")

# Test Case 1
print("Invers A1:\n", invers_matriks(A1))
# Penjelasan:
# Determinan ≠ 0, sehingga invers dapat dihitung

# Test Case 2
print("\nInvers A4:\n", invers_matriks(A2))
# Penjelasan:
# Determinan = 0 → tidak memiliki invers

# Test Case 3
print("\nInvers A3:\n", invers_matriks(A3))
# Penjelasan:
# Matriks memiliki invers karena determinan ≠ 0

1 B3

=== TEST CASE INVERS MATRIKS ===
Invers A1:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Invers A4:
 Matriks tidak invertible (determinan = 0)

Invers A3:
 [[2.  1. ]
 [1.5 0.5]]


# FUNGSI MANUAL TANPA BUILT-IN HIGH-LEVEL

## PERKALIAN MANUAL 

In [24]:
def perkalian_matriks_manual(X, Y):
    """
    Perkalian matriks manual (tanpa NumPy)
    X: matriks m x n (list 2D)
    Y: matriks n x p (list 2D)
    """

    m = len(X)          # jumlah baris X
    n = len(X[0])       # jumlah kolom X
    n2 = len(Y)         # jumlah baris Y
    p = len(Y[0])       # jumlah kolom Y

    # Validasi syarat perkalian matriks
    if n != n2:
        raise ValueError("Ukuran matriks tidak cocok untuk dikalikan")

    # Inisialisasi matriks hasil (m x p) dengan nol
    Z = []
    for i in range(m):
        baris = []
        for j in range(p):
            baris.append(0)
        Z.append(baris)

    # Proses perkalian manual (3 loop)
    for i in range(m):          # baris X
        for j in range(p):      # kolom Y
            for k in range(n):  # penjumlahan
                Z[i][j] += X[i][k] * Y[k][j]

    return Z

print("\n=== TEST CASE 1 PERKALIAN MATRIKS MANUAL 2x2 ===")
A1 = [
    [1, 2],
    [3, 4]
]

B1 = [
    [5, 6],
    [7, 8]
]

C1 = perkalian_matriks_manual(A1, B1)

print("Matriks A1:")
print(A1)
print("Matriks B1:")
print(B1)
print("Hasil A1 x B1:")
print(C1)

print("\n=== TEST CASE 2 PERKALIAN MATRIKS MANUAL 2x3 dan 3x2 ===")
A2 = [
    [1, 2, 3],
    [4, 5, 6]
]

B2 = [
    [7, 8],
    [9, 10],
    [11, 12]
]

C2 = perkalian_matriks_manual(A2, B2)

print("Matriks A2:")
print(A2)
print("Matriks B2:")
print(B2)
print("Hasil A2 x B2:")
print(C2)

print("\n=== TEST CASE 3 Negatif & Nol ===")
A2 = [
    [1, 2, 3],
    [4, 5, 6]
]

B2 = [
    [7, 8],
    [9, 10],
    [11, 12]
]

C2 = perkalian_matriks_manual(A2, B2)


print("Matriks A2:")
print(A2)
print("Matriks B2:")
print(B2)
print("Hasil A2 x B2:")
print(C2)



=== TEST CASE 1 PERKALIAN MATRIKS MANUAL 2x2 ===
Matriks A1:
[[1, 2], [3, 4]]
Matriks B1:
[[5, 6], [7, 8]]
Hasil A1 x B1:
[[19, 22], [43, 50]]

=== TEST CASE 2 PERKALIAN MATRIKS MANUAL 2x3 dan 3x2 ===
Matriks A2:
[[1, 2, 3], [4, 5, 6]]
Matriks B2:
[[7, 8], [9, 10], [11, 12]]
Hasil A2 x B2:
[[58, 64], [139, 154]]

=== TEST CASE 3 Negatif & Nol ===
Matriks A2:
[[1, 2, 3], [4, 5, 6]]
Matriks B2:
[[7, 8], [9, 10], [11, 12]]
Hasil A2 x B2:
[[58, 64], [139, 154]]


## LINEAR -> ELIMINASI GAUUS