# **OPERASI DASAR MATRIKS**

## PENJUMLAHAN MATRIKS

In [9]:
import numpy as np

# FUNGSI PENJUMLAHAN MATRIKS
def penjumlahan_matriks(A, B):
    """
    Menjumlahkan dua matriks 2x2
    Syarat: Ukuran matriks A dan B harus sama
    """
    return A + B

A1 = np.array([[1, 2],
               [3, 4]])
B1 = np.array([[5, 6],
               [7, 8]])

A2 = np.array([[0, 0],
               [0, 0]])
B2 = np.array([[2, 3],
               [4, 5]])

A3 = np.array([[-1, 2],
               [3, -4]])
B3 = np.array([[4, -2],
               [-3, 1]])
print("=== TEST CASE PENJUMLAHAN MATRIKS ===")

# Test Case 1
print("Input:\n", A1, "\n+\n", B1)
print("Output:\n", penjumlahan_matriks(A1, B1))

# Test Case 2
print("\nInput:\n", A2, "\n+\n", B2)
print("Output:\n", penjumlahan_matriks(A2, B2))
# Penjelasan:
# Matriks nol tidak mengubah nilai matriks lain

# Test Case 3
print("\nInput:\n", A3, "\n+\n", B3)
print("Output:\n", penjumlahan_matriks(A3, B3))
# Penjelasan:
# Bilangan negatif dan positif dijumlahkan normal

=== TEST CASE PENJUMLAHAN MATRIKS ===
Input:
 [[1 2]
 [3 4]] 
+
 [[5 6]
 [7 8]]
Output:
 [[ 6  8]
 [10 12]]

Input:
 [[0 0]
 [0 0]] 
+
 [[2 3]
 [4 5]]
Output:
 [[2 3]
 [4 5]]

Input:
 [[-1  2]
 [ 3 -4]] 
+
 [[ 4 -2]
 [-3  1]]
Output:
 [[ 3  0]
 [ 0 -3]]


## PENGURANGAN MATRIKS

In [ ]:
import numpy as np
def pengurangan_matriks(A, B):
    """
    Mengurangkan matriks B dari matriks A
    """
    return A - B

A1 = np.array([[1, 2],
            [3, 4]])
B1 = np.array([[5, 6],
            [7, 8]])

A2 = np.array([[0, 0],
            [0, 0]])
B2 = np.array([[2, 3],
            [4, 5]])

A3 = np.array([[-1, 2],
            [3, -4]])
B3 = np.array([[4, -2],
            [-3, 1]])
print("\n=== TEST CASE PENGURANGAN MATRIKS ===")
# Test Case 1

print("Input:\n", A1, "\n-\n", B1)
print("Output:\n", pengurangan_matriks(A1, B1))

# Test Case 2
print("\nInput:\n", B2, "\n-\n", A2)
print("Output:\n", pengurangan_matriks(B2, A2))
# Penjelasan:
# Matriks nol tidak mengubah nilai matriks lain

# Test Case 3

print("\nInput:\n", A3, "\n+\n", B3)
print("Output:\n", pengurangan_matriks(A3, B3))
# Penjelasan:
# Bilangan negatif dan positif dijumlahkan normal


=== TEST CASE PENGURANGAN MATRIKS ===
Input:
 [[1 2]
 [3 4]] 
-
 [[5 6]
 [7 8]]
Output:
 [[-4 -4]
 [-4 -4]]

Input:
 [[2 3]
 [4 5]] 
-
 [[0 0]
 [0 0]]
Output:
 [[2 3]
 [4 5]]

Input:
 [[-1  2]
 [ 3 -4]] 
+
 [[ 4 -2]
 [-3  1]]
Output:
 [[-5  4]
 [ 6 -5]]


## PERKALIAN MATRIKS

In [12]:
import numpy as np
def perkalian_matriks(A, B):
    """
    Mengalikan dua matriks menggunakan perkalian matriks (dot product)
    """
    return np.dot(A, B)

A1 = np.array([[1, 2],
            [3, 4]])
B1 = np.array([[5, 6],
            [7, 8]])

A2 = np.array([[0, 0],
            [0, 0]])
B2 = np.array([[2, 3],
            [4, 5]])

A3 = np.array([[-1, 2],
            [3, -4]])
B3 = np.array([[4, -2],
            [-3, 1]])

print("\n=== TEST CASE PERKALIAN MATRIKS ===")

print("Input:\n", A1, "\nx\n", B1)
print("Output:\n", perkalian_matriks(A1, B1))

# Test Case 2
print("\nInput:\n", B2, "\nx\n", A2)
print("Output:\n", perkalian_matriks(B2, A2))
# Penjelasan:
# Matriks nol tidak mengubah nilai matriks lain

# Test Case 3

print("\nInput:\n", A3, "\nx\n", B3)
print("Output:\n", perkalian_matriks(A3, B3))


=== TEST CASE PERKALIAN MATRIKS ===
Input:
 [[1 2]
 [3 4]] 
x
 [[5 6]
 [7 8]]
Output:
 [[19 22]
 [43 50]]

Input:
 [[2 3]
 [4 5]] 
x
 [[0 0]
 [0 0]]
Output:
 [[0 0]
 [0 0]]

Input:
 [[-1  2]
 [ 3 -4]] 
x
 [[ 4 -2]
 [-3  1]]
Output:
 [[-10   4]
 [ 24 -10]]


## DETERMINAN MATRIKS

## INVERS MATRIKS